name: Update Index

on: push

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.11.0

      - name: Run Updater & Update Index
        run: node update-index.js

      - name: Git Commit/Push Changes
        uses: actions-x/commit@v6
        with:
          email: kiracarmaganonal@gmail.com
          message: Update extension index.
          token: ${{ secrets.GITHUB_TOKEN }}
          # Whether to perform force push
          force: 1
